version: "3.9"

services:
 database:
    image: postgres
    restart: always
    environment:
     POSTGRES_USER: ${POSTGRESQL_USERNAME}
     POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
     POSTGRES_DB: ${POSTGRESQL_DATABASE}
    volumes:
      - pgdata:/data/postgres
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${POSTGRESQL_PORT}:5432

 redis:
  image: redis:alpine
  ports:
   - ${REDIS_PORT}:${REDIS_PORT}

volumes:
 pgdata:
  driver: local
