version: "3.9"

services:
 postgres:
    image: postgres
    restart: always
    environment:
     POSTGRES_USER: ${POSTGRESQL_USERNAME}
     POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
     POSTGRES_DB: ${POSTGRESQL_DATABASE}
    ports:
      - ${POSTGRESQL_PORT}:5432
      
 redis:
  image: redis:alpine
  ports:
   - ${REDIS_PORT}:${REDIS_PORT}
